train_file: '/kaggle/input/power-data-en/train/train.json'
test_file: '/kaggle/input/power-data-en/test/test.json'
query_file: '/kaggle/input/power-data-en/test/test.json'
gallery_file: '/kaggle/input/power-data-en/gallery_image_root/gallery_image_root.json'
train_image_root: '/kaggle/input/power-data-en/train/images'
test_image_root: '/kaggle/input/power-data-en/test/images'
gallery_image_root: '/kaggle/input/power-data-en/gallery_image_root/images'

vit: 'large'
vit_grad_ckpt: True
vit_ckpt_layer: 0
image_size: 224
batch_size_train: 16
batch_size_test: 16

# optimizer
weight_decay: 0.05
init_lr: 1e-4
min_lr: 1e-7
k_test: 10
max_words: 80
window_size: 50

#CL
max_epoch: 50
task: ['BYQ', 'DZGL', 'FDJ', 'JYZ', 'NC', 'RQLJ', 'SDDX', 'SDGT', 'SLJ', 'ZQLJ']
base_mode: 'seqF'

